# app/config/security.yml
security:
    always_authenticate_before_granting: true
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        login_firewall:
            pattern:   ^/(login$|register|resetting|$)
            anonymous: ~

        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
                default_target_path: home
            logout:
                path:   /logout
                target:  /
            provider: fos_userbundle

    access_control:
    - { path: ^/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/resetting, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/, roles: ROLE_USER }
    
    role_hierarchy:
        ROLE_SHOP:               ROLE_USER
        ROLE_BUYER:            ROLE_USER
